name: Build Docker Container for Hospital SDK & Push to Docker Hub

on:
  push:
    branches:
      - docker-client

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build web container image for hospital-sdk
        run: |
          cd hospital-sdk
          docker build -t sms7/hospital-sdk:latest -t sms7/hospital-sdk:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}  .
      - name: Push container
        run: docker push sms7/hospital-sdk:latest
